theme: jekyll-theme-minimal
title: Welcome to Pranav's site
github:
  is_project_page: false
  is_user_page: false
navigation:
  - title: Ravi's site
    link: https://ravi.bhoraskar.com
  - title: Antariksh's site
    link: http://www.antarikshbothale.com/
